### ISSUE TITLE
Pause and close recording makes app crash

### ISSUE THREAD

**Issue by MarkoIndaco** [SimpleMobileTools/Simple-Voice-Recorder#105]
Hi, as the title I notice this issue yesterady. Step to reproduce:
1 - Start recording
2 - Pause the recording
3 - Close the recording

If you try instead to pause - unpause - stop recording then it stops and save the file properly.
Well, nothing crititcal, just to inform.

crDroid 7.5 (Android 11 based)

**Comment by tibbi** [comment]
what app version are you using? So your device is rooted?

**Comment by MarkoIndaco** [comment]
App version is 5.6.5
The smarphone is Xiaomi Mi 9 Lite, rooted Magisk 24.3
Thank you for support

**Comment by tibbi** [comment]
as noone else reported such an issue, it will be caused by rooting though, we arent responsible for that
