### ISSUE TITLE
Cannot delete recordings

### ISSUE THREAD

**Issue by mase76** [SimpleMobileTools/Simple-Voice-Recorder#111]
Hi,
deleting a recording does not have any effect. I have to delete it with a filemanager.

**Comment by tibbi** [comment]
why not? What happens as you try deleting it? What app and OS version are you using at all?

**Comment by mase76** [comment]
I am using Crdroid 8.5 (Android 12) Vanilla. The app version is 5.7.1 from F-droid. There is no error message. The file just stays there when deleting.

**Comment by tibbi** [comment]
can you create a screen recording?

**Comment by mase76** [comment]
![recording_20220604_182427](https://user-images.githubusercontent.com/2173853/172016279-5792d756-07e3-4781-93fc-b67a6ccc7444.gif)

**Comment by mase76** [comment]
I get this message, when trying to rename the recording.
![Screenshot_20220604-183053_Diktiergerät](https://user-images.githubusercontent.com/2173853/172016535-f5f033b2-091a-4b29-999d-c43fcf4cef6f.png)

**Comment by tibbi** [comment]
try reinstalling the app

**Comment by mase76** [comment]
I already did. I wonder that the app does not ask for file and media permissions.

**Comment by tibbi** [comment]
right, it should. Does deleting work in our Simple Music Player? Guess it is some system issue with your rooted device.

**Comment by mase76** [comment]
Yes, your music player asks for the permission, and deleting files works with it.

**Comment by tibbi** [comment]
ok, we will see what happens after updating the music player and voice recorder soon. If they will work the same or not.

**Comment by TownCube** [comment]
Android 12 not-rooted and I have the same issue. For me it seems to occur if you try to move the recording folder somewhere other then the default or you try and manage files not created since the last install of the recorder.

For me me the deletion appears to work, but when you restart the app the file comes back. Renaming produces the correct error message.

**Comment by mase76** [comment]
The issue is still there in version 5.8.0. Deleting works when I use the default path. When I change it, the issue is there. The issue stays, when I change back to the dafault path.

**Comment by parity123** [comment]
This was successful for me:
1. Use a File Manager to delete audio files
2. Go into App Info/Storage and Clear Data
3. Uninstall Voice Recorder
4. Install Voice Recorder
