### ISSUE TITLE
Rename en-GB to en-US

### ISSUE THREAD

**Issue by licaon-kter** [SimpleMobileTools/Simple-Voice-Recorder#132]
If there's no metadata that matches current locale (eg. `ro-RO`), F-Droid tries to use `en-US` but if that's [not available either](https://github.com/SimpleMobileTools/Simple-Voice-Recorder/tree/master/fastlane/metadata/android) it will show first metadata language code found eg. Arabic

**Comment by tibbi** [comment]
cant you set it to en-GB? Thats what we have as default on Google Play.

**Comment by licaon-kter** [comment]
Set which one, F-Droid last resort locale? 

Define "we"?

**Comment by tibbi** [comment]
maybe us on our side?

**Comment by licaon-kter** [comment]
Thanks, will see in the next release how screenshots behave.

**Comment by tibbi** [comment]
just released Simple Contacts Pro 6.21.0 with en-US set as the default language, githubs fastlane is synced with Google Play too

**Comment by licaon-kter** [comment]
Thanks
