### ISSUE TITLE
Add FLAC format support

### ISSUE THREAD

**Issue by PatrykMis** [SimpleMobileTools/Simple-Voice-Recorder#133]
MediaFormat and MediaCodec supports FLAC (Free Lossless Audio Codec), so glad to see this format supported in this app too. It could be done like in BCR:

* https://github.com/chenxiaolong/BCR/blob/master/app/src/main/java/com/chiller3/bcr/format/FlacContainer.kt
* https://github.com/chenxiaolong/BCR/blob/master/app/src/main/java/com/chiller3/bcr/format/FlacFormat.kt

**Comment by tibbi** [comment]
child of #29

**Comment by rokejulianlockhart** [comment]
@tibbi, probably worth closing as invalid rather than completed, then.

**Comment by tibbi** [comment]
which do you mean?
