### ISSUE TITLE
Add ability to select recording source

### ISSUE THREAD

**Issue by PatrykMis** [SimpleMobileTools/Simple-Voice-Recorder#139]
Default is CAMCORDER, but others sometimes are useful - e.g. UNPROCESSED, especially when recording in lossless formats like WAV or (possibly) FLAC.

**Comment by tibbi** [comment]
you mean source or file extension?

**Comment by PatrykMis** [comment]
@tibbi  source.
https://developer.android.com/reference/android/media/MediaRecorder.AudioSource

**Comment by PatrykMis** [comment]
Of course I mean UNPROCESSED not RAW (corrected).

**Comment by tibbi** [comment]
will be added in 5.10.3

**Comment by PatrykMis** [comment]
Already in [5.10.3](https://github.com/SimpleMobileTools/Simple-Voice-Recorder/releases/tag/5.10.3). Thank you!
