### ISSUE TITLE
Android Native Documents UI

### ISSUE THREAD

**Issue by maemunman** [SimpleMobileTools/Simple-Voice-Recorder#150]
I made this as an issue in Simple SMS, but it's more proper to have it here.

It would be incredible if Simple Voice Recorder had an entry in the native Documents UI, so that, for example, you can choose to *add an attachment* in your email app, choose Simple Voice Recorder on the following screen, and record a new message on the fly to attach to the email, and not necessarily store it on the device.

It would then of course enhance a whole load of other apps, including Simple SMS

![image108](https://user-images.githubusercontent.com/32847759/194438459-c8ae73f8-f1e0-4d71-a354-cea096253167.png)

**Comment by tibbi** [comment]
that is unrelated to the documents UI, it needs some intent handling like Record audio. Ill keep an eye on it, but close this one as it is unrelated.
