### ISSUE TITLE
[question] does this app record the audio in the highest quality?

### ISSUE THREAD

**Issue by nameless326** [SimpleMobileTools/Simple-Voice-Recorder#166]
and, what's the difference between each "Audio source"?

![screenshot_20221201-143722.png](https://user-images.githubusercontent.com/85243826/205122269-30596caa-c824-4d41-afa3-37488c17aef3.png)

which one should I pick to record the audio in the highest quality?

**Comment by tibbi** [comment]
well, it can depend on your device. Just try all of them and see which one works the best for you
