### ISSUE TITLE
Select Directory?

### ISSUE THREAD

**Issue by indeedwatson** [SimpleMobileTools/Simple-Voice-Recorder#18]
I'd like to use syncthing to back up my recordings, but the recorder won't let me select a directory where to save.

**Comment by paulle** [comment]
It would be a great feature, if one can store the voice records on the SD- card.

**Comment by bluebirch** [comment]
A related question. When I first installed it, it used its own folder (`Simple Voice Recorder`), but not it saves recordings in the `Music`folder. Why? The only thing I can recall has changed is an upgrade of Android 9 to 10.

**Comment by tibbi** [comment]
Sure, thats why. The storage related things keep changing almost in every Android version. Im trying not having access to the Storage, unless it is necessary. So from Android 10+ or so, the app has no access to your files.

**Comment by metalx1000** [comment]
I understand that Android storage permissions are a pain.
Maybe instead of putting it in the "Music" folder it could be put in a sub directory of the music folder.
Something like "Music/VoiceRecordings".
This way I could tell my music player to ignore that directory so I don't have my voice recordings randomly play while I'm driving in my car and I can tell Syncthing or Nextcloud to sync just that folder and not all my music.

**Comment by jwsp1** [comment]
> I understand that Android storage permissions are a pain.
> Maybe instead of putting it in the "Music" folder it could be put in a sub directory of the music folder.
> Something like "Music/VoiceRecordings".
> This way I could tell my music player to ignore that directory so I don't have my voice recordings randomly play while I'm driving in my car and I can tell Syncthing or Nextcloud to sync just that folder and not all my music.

Having the same issue. Listening to music and then to your recordings is a pain. 
I wouldn't store it in "Music" (are voice recordings music after all?), rather in the root folder with a folder "Sounds": `Intern/Sounds/VoiceRecorder`

**Comment by stevenleeS0ht** [comment]
>Sure, thats why. The storage related things keep changing almost in every Android version. Im trying not having access to the Storage, unless it is necessary. So from Android 10+ or so, the app has no access to your files.

But how the other Apps solve the storage issue which is mentioned by you above?

**Comment by tibbi** [comment]
They can still use the old way, but I want to move away from it gradually.

**Comment by stevenleeS0ht** [comment]
@tibbi , However `Simple File Manager` is the sister project of `Simple Voice Recorder`. How does it solve the problem of storage issue mentioned above?

**Comment by stevenleeS0ht** [comment]
@tibbi , probably, the most simple way to solve that is let user select their own favorite path. If the target directory not exist. Then explicitly ask user to choose one.

**Comment by tibbi** [comment]
file managers will be able to access files in the future too

**Comment by tibbi** [comment]
starting with version 5.5.0 on Android 10+ all recordings will be saved into an own folder Recordings within the Music folder. It might be customizable later, but it is a bit more difficult to do, so this should do it for now.

**Comment by tibbi** [comment]
customization for all devices will be added in the next app version 5.7.1 released soon

**Comment by landry314** [comment]
I can not change the directory. Tapping on "Save Recordings in" does nothing.

LOS 20.0 on Pixel 5

**Comment by Aga-C** [comment]
@landry314 This has been fixed in the latest version 5.12.3.

**Comment by landry314** [comment]
hasnt been pushed to fdroid i guess...

**Comment by Aga-C** [comment]
As usual it will take a few days.
