### ISSUE TITLE
Add automatic speech recognition

### ISSUE THREAD

**Issue by JCGoran** [SimpleMobileTools/Simple-Voice-Recorder#183]
With the release of [whisper.cpp](https://github.com/ggerganov/whisper.cpp), it's possible to do fully offline automatic speech recognition with an acceptable word error rate, and there is even an [example Android app](https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.android) available (MIT licensed). The [original code](https://github.com/openai/whisper) and the model weights are all MIT licensed as well.

I don't know if implementing this particular feature would be outside of the scope of this project, but an Android FOSS audio recorder app with decent transcription would be of incredible value to the whole ecosystem.

**Comment by tibbi** [comment]
that isnt on the roadmap
