### ISSUE TITLE
Is it possible to have some faster ways of start and stop recording?

### ISSUE THREAD

**Issue by zznww** [SimpleMobileTools/Simple-Voice-Recorder#186]
This app can make a quick start and stop of recording via widget. Thank you for the great work!

I an wondering if it is possible to make it even faster, e.g. start/stop recording upon physical volume key or power button press even when screen is off. This can be really useful in use cases like voice memo/note, which allows quick and short recording without looking at the screen, significantly reduce the steps required to start.  as a typical work flow would yet require a few steps to start: 1) unlock the phone 2) navigate and locate the widget icon 3) click the icon to start and stop.

**Comment by tibbi** [comment]
that isnt on the roadmap, doing it with 1 click is quick enough..
