### ISSUE TITLE
BUG: Wrong filecontainer (.mp3) is used, instead of right one (.m4a)

### ISSUE THREAD

**Issue by huuhaa** [SimpleMobileTools/Simple-Voice-Recorder#19]
It seems that app is using wrong filecontainer (.mp3), saves audio to file by using FAAC codec, which is good codec to use, but filecontainer should be (.m4a). Sure (.aac) would also work but for good id3 tag support better choose (.m4a).

Sound works ok with android device and also at laptop with .mp3 container too, but...

ffmpeg -ss 00:00:02 -t 00:00:04 -i test.mp3 -acodec copy clip.mp3

[mp3 @ 0x55c041a5eac0] Invalid audio stream. Exactly one MP3 audio stream is required.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

As an result there is clip.mp3 which obviously doesn't work

After manually renamed to .m4a 

ffmpeg -ss 00:00:02 -t 00:00:04 -i test.m4a -acodec copy clip.m4a

ffmpeg copies clip without any error and results working audioclip.

So luckily there's easy solution to fix this, change container to .m4a

**Comment by huuhaa** [comment]
Just noticed that this is related to following:

https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/1

Don't know why that one is closed though, since solution should be quite simple.

**Comment by tibbi** [comment]
just upgrade to 5.2.0, m4a is used already
