### ISSUE TITLE
Pause keeps blinking faster when settings icon clicked

### ISSUE THREAD

**Issue by Uniquely6958** [SimpleMobileTools/Simple-Voice-Recorder#191]
Steps:
1. Start recording
2. Pause
3. Click on settings
4. Press back
5. Repeat to check

The pause button blinks faster and faster. It should blink at a constant rate.
Version 5.11.2 from FDroid

**Comment by Uniquely6958** [comment]
#192

**Comment by tibbi** [comment]
should be fixed in 5.11.3
