### ISSUE TITLE
audio files added to Recordings folder don't show in app

### ISSUE THREAD

**Issue by itswck** [SimpleMobileTools/Simple-Voice-Recorder#199]
I have this app on 2 phones. I made a recording on "phone 1" and transferred it to the correct Recordings folder in "phone 2". For some reason though, the recording does not show in the app on "phone 2".

Both phones are Google Pixel 6a, with GrapheneOS, 
Phone 1: Simple Voice Recorder v5.11.3
Phone 2: Simple Voice Recorder v5.11.2

**Comment by tibbi** [comment]
thats sadly how the system works due to system restrictions. The app only has access to the files it created itself.

**Comment by itswck** [comment]
Thank you for clarifying
