### ISSUE TITLE
Setting to turn off adjustment of window size

### ISSUE THREAD

**Issue by RustoMCSpit** [SimpleMobileTools/Simple-Voice-Recorder#202]
In the bottom window, the amount of visible notes can jump drastically. There should be an option to set how many notes are visible / an octave mode that after hearing the first new note it will show 6 notes above it and 6 below.  This is a general idea, tweak at will

**Comment by tibbi** [comment]
what do you mean, what notes?

**Comment by RustoMCSpit** [comment]
> what do you mean, what notes?

the bottom panel automatically adjusts the amount of notes shown, id like it to be locked to an octave (or any other amount) and have the panel not move or adjust the amount of notes as a setting

**Comment by tibbi** [comment]
can you sent a screenshot of what you mean? You seem to be mistaking the app.

**Comment by RustoMCSpit** [comment]
Oh my you are rigjt, apologies this is for a different app
