### ISSUE TITLE
[Feature Request] Option to stop button flashing when recording is stopped

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Voice-Recorder#207]
https://github.com/SimpleMobileTools/Simple-Voice-Recorder/assets/75314629/a9fa43be-c6a9-4b58-b5b1-8d881c3bbda8

**Comment by tibbi** [comment]
what do you mean, what flashes?

**Comment by inson1** [comment]
I mean second button is flashing if you stop recording

**Comment by tibbi** [comment]
thats pause, it works as intended
