### ISSUE TITLE
Add OGG Vorbis and OPUS formats

### ISSUE THREAD

**Issue by HT-7** [SimpleMobileTools/Simple-Voice-Recorder#212]
The current formats are M4A (which uses AAC) and MP3. Please add the OGG and OPUS formats developed by XIPH, for they are open-source and patentless.

**Comment by Aga-C** [comment]
There is already Opus support in the app, but it requires Android 10+. If you have older Android, there is an issue for adding Opus support to them: https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/178.

**Comment by HT-7** [comment]
I see. I am changing the title for clarity. Vorbis existed for much longer.
