### ISSUE TITLE
Record audio without interfering with the video camera

### ISSUE THREAD

**Issue by HT-7** [SimpleMobileTools/Simple-Voice-Recorder#215]
Currently, a video recorder app is unable to record while the audio recorder is recording in the background. 

I suggest that the app records in background without interfering with the video camera, so both the video camera can record and the voice recorder. Since desktop computers and laptops are able to have multiple programs access the microphone at the same time, it must be technically possible on mobile phones too.

Perhaps such a feature would be only possible for users who have root access.

**Comment by RustoMCSpit** [comment]
kinda related but which microphone is best, the settings provide sm options it confuses me

**Comment by tibbi** [comment]
I dont think it is possible

**Comment by HT-7** [comment]
> I dont think it is possible

Not even with root access?
