### ISSUE TITLE
Recordings over 15 seconds dont get saved correctly

### ISSUE THREAD

**Issue by nishkaamprem** [SimpleMobileTools/Simple-Voice-Recorder#217]
#185

**Comment by nishkaamprem** [comment]
![Screenshot_20230821_222827_Voice Recorder](https://github.com/SimpleMobileTools/Simple-Voice-Recorder/assets/105187044/74073017-2f4d-4547-8984-f2f501624ef6)

**Comment by tibbi** [comment]
duplicate of #185
