### ISSUE TITLE
Completely unusable for recording music - crackles

### ISSUE THREAD

**Issue by metronidazole** [SimpleMobileTools/Simple-Voice-Recorder#219]
The app works fine for recording conversations but it is completely useless for recording music. 

Even with 320kbps quality, the recording has many crackles and is very tinny. As a test, I recording the same thing with google camera and it was fine. Not sure what the cause is but I'm sure you'll be able to replicate it yourself. This is with the pixel 5.

**Comment by tibbi** [comment]
try selecting a different audio source in the app settings. Also not sure why are you mixing a camera with voice recorder.
