### ISSUE TITLE
app breaks when you hit top right info button on new update

### ISSUE THREAD

**Issue by RustoMCSpit** [SimpleMobileTools/Simple-Voice-Recorder#221]

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by RustoMCSpit** [comment]
> what app and OS version are you using?

latest app, grapheneos, lawnchair launcher

**Comment by tibbi** [comment]
I mean versions, some numbers

**Comment by RustoMCSpit** [comment]
> I mean versions, some numbers

the most recent version of each (lawnchair githuh, not gplay)

**Comment by tibbi** [comment]
could you tell some numbers? They are the most recent for you, might not be for everyone. And they wont be the most recent forever, something newer will eventually be released.

**Comment by RustoMCSpit** [comment]
> could you tell some numbers? They are the most recent for you, might not be for everyone. And they wont be the most recent forever, something newer will eventually be released.

graphene [2023090600](https://grapheneos.org/releases#2023090600)

voice recorder 5.12.1

Lawnchair 12.1.0 Alpha 4

**Comment by Aga-C** [comment]
I also have this bug on Android 13.
