### ISSUE TITLE
Cannot update to latest version 

### ISSUE THREAD

**Issue by lipici** [SimpleMobileTools/Simple-Voice-Recorder#226]
I downloaded for all apps latest version from github because on fdroid last version its from 1 month ago or more and cannot update. Says update its incompatible.
How its possible ?

**Comment by Aga-C** [comment]
F-Droid version is compiled and signed by F-Droid, not Simple Mobile Tools, so you can't update F-Droid version with GitHub version. You've to wait until it's released on F-Droid or uninstall the F-Droid version and install the GitHub one.

**Comment by lipici** [comment]
Ok, thank you, idk why i remember that it worked some time ago.
