### ISSUE TITLE
Offline, privacy-respecting speech to text

### ISSUE THREAD

**Issue by emes81** [SimpleMobileTools/Simple-Voice-Recorder#229]
Futo has partially delivered on this with an excellent FOSS solution:

https://gitlab.futo.org/alex/voiceinput
https://voiceinput.futo.org/

But the Futo solution currently works within other apps only and is not integrated directly into a voice recorder app. Adding Futo's speech-to-text capabilities to Simple Voice Recorder would make a voice recorded easily on par with Google's proprietary app.

**Comment by tibbi** [comment]
dont really expect having something like that in this app

**Comment by RustoMCSpit** [comment]
> Futo has partially delivered on this with an excellent FOSS solution:
> 
> https://gitlab.futo.org/alex/voiceinput https://voiceinput.futo.org/
> 
> But the Futo solution currently works within other apps only and is not integrated directly into a voice recorder app. Adding Futo's speech-to-text capabilities to Simple Voice Recorder would make a voice recorded easily on par with Google's proprietary app.

would also be able to allow for a transcript so you coulf have a search bar and go through your voice recordings and you could click through the exact moment that word was said in the voice recordings. so if i typed 'jack' it may find 4 hits from the past 4 months:
file191: 00:07
file179: 12:23, 16:30 
file73: 06:42 

you could then click on those moments to find the one youre looking for.

this could also be used for tagging, for example, if im working on a project called 'block runner' i could search for all mentions and tag them all easily

**Comment by RustoMCSpit** [comment]
> dont really expect having something like that in this app

will you ever change your mind / how much of a donation would sway you?

**Comment by Bonboon229** [comment]
Dude, stop

**Comment by inson1** [comment]
@Bonboon229 ?
