### ISSUE TITLE
Continuos Record

### ISSUE THREAD

**Issue by GuiSousa135** [SimpleMobileTools/Simple-Voice-Recorder#238]
I use and like Simple Voice Record very much, but I would like to see the continuous recording function of audio in backgroud (like a security camera with dvr that keeps recent recordings and excludes old recordings). It would enable the user to record 24 hours continuously, without the file corrupting or occupying much memory, since it would be recorded in parts (such as 30 minuntos, 1 hour recording). A very cool project for android that has this function is the Alibi recorder (https://github.com/Myzel394/Alibi).

**Comment by tibbi** [comment]
that isnt really the target usecase of this app
