### ISSUE TITLE
Feature Request: Keep screen on during recording

### ISSUE THREAD

**Issue by 13rac1** [SimpleMobileTools/Simple-Voice-Recorder#239]
Hi! Thanks for making this.

It would be helpful/useful if the screen would _optionally_ stay on during recording.  Setting the [`FLAG_KEEP_SCREEN_ON`](https://developer.android.com/training/scheduling/wakelock#screen) is probably sufficient.

**Comment by tibbi** [comment]
what is the issue here? We dont care if the screen is on or off

**Comment by 13rac1** [comment]
😆  you might not care, but I do. I'm currently running one of these "caffeine" sleep disabling apps to keep the screen on while recording, but it's inconvenient. I prefer to see the recording waveform to keep track of background noise, know I am speaking loud enough, and to track overall recording status. Does that make sense?

**Comment by tibbi** [comment]
I dont really plan keeping the screen on while recording audio, that is not the expected behaviour

**Comment by 13rac1** [comment]
I know, but that's why I asked if it could become expected behavior. No problem though, I'll fork it.
