### ISSUE TITLE
Feature: Option for alternative (more readable) filename patterns

### ISSUE THREAD

**Issue by camoz** [SimpleMobileTools/Simple-Voice-Recorder#246]
Right now, my recordings are saved as e.g. `2023_12_22_20_46_18.m4a`, but I would like them to be saved as something like:

- `2023-12-22_204618.m4a` or
- `20231222_204618.m4a` or
- `2023-12-22_20-46-18.m4a`

The reason is because it's easier to visually (and programmatically) distinguish the date from the time. Android saves camera photos as `IMG_20231210_051153_297.jpg` by the way.

I guess one could either implement a set of formats to choose from, or a field where one could enter a custom pattern like [Markor](https://github.com/gsantner/markor) does; it provides an option where one can enter a pattern for [`SimpleDateFormat`](https://developer.android.com/reference/android/icu/text/SimpleDateFormat) (in case this is already used by Simple Voice Recorder, idk).

(FWIW, I have my `date and time format` in the settings currently set to `2023-02-15`.)

**Comment by inson1** [comment]
@camoz SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

**Comment by camoz** [comment]
I see, thanks for letting me know!
