### ISSUE TITLE
[Feature] Switch audio source

### ISSUE THREAD

**Issue by jSadoski** [SimpleMobileTools/Simple-Voice-Recorder#27]
While connected to bluetooth, my default phone app allows me to switch between my bluetooth microphone and the built-in phone microphone. It would be very useful if Simple Voice Recorder had a similar feature!

Thank you for this app and the line of tools you make.

**Comment by morfikov** [comment]
I also wanted to ask about this feature. Currently I know only one app that is able to switch the mic source, i.e. [android-audio-recorder](https://gitlab.com/axet/android-audio-recorder).

**Comment by tibbi** [comment]
will be added in 5.10.3
