### ISSUE TITLE
Recording complete toast covers record button

### ISSUE THREAD

**Issue by nvllsvm** [SimpleMobileTools/Simple-Voice-Recorder#28]
**Current**
When recording is stopped, a toast notification is displayed over the record button. 

**What's the problem?**
Displaying a toast over an actionable button makes it more difficult to press the button. I often record voice notes back-to-back.

**Suggestion**
Move the toast to the center of the screen.

**Screenshot**

![Screenshot_20201002-155111_Voice_Recorder](https://user-images.githubusercontent.com/6550543/98198489-113e8f00-1ef7-11eb-9c4f-8f06a5db56cb.png)

**Comment by tibbi** [comment]
you can click through it, no issue with that. I dont think it needs a change.

**Comment by nvllsvm** [comment]
From a usability perspective, it always causes slight hesitation when I see it.
