### ISSUE TITLE
Allow renaming file after end of recording

### ISSUE THREAD

**Issue by raphraph** [SimpleMobileTools/Simple-Voice-Recorder#32]
It would be nice to be able to rename the file that just has been recorded (instead of opening the file manager app > find file > rename it) as it would ease finding the recorded content when looking for it later.

Thanks for this great app 👍

**Comment by tibbi** [comment]
you can already swipe right to the Player tab, select the wanted file and use Rename at the top menu. I dont really want to do it differently.

**Comment by raphraph** [comment]
Great thanks !! I actually didn't notice the player tab so I did not see this feature. Sorry and thanks for taking the time to answer.
