### ISSUE TITLE
Different licenses listed

### ISSUE THREAD

**Issue by metalx1000** [SimpleMobileTools/Simple-Voice-Recorder#39]
Fdroid has this app listed as an Apache License 2.0 
https://f-droid.org/en/packages/com.simplemobiletools.voicerecorder/

Here on github it's listed as a GPLv3 License.
The Apache 2.0 License is compatible with the GPLv3, but I'm not sure it works the other way.

I'm assuming one of these are incorrect, so I thought I would point it out.
One difference is Apache allows sublicensing, but the GPLv3 doesn't.
So, it could make a difference on how the code is used.

**Comment by tibbi** [comment]
it is wrong in f-droid

**Comment by joaquinyab** [comment]
so, can i use this code? i mean i will change it... but can i used  this code like a base code for my app?

**Comment by metalx1000** [comment]
@joaquinyab Depends on what license you are using for your project.  
GPLv3 guarantees the user's freedom down the line.  Hopefully you're creating an app in the same way.
If you plan on using the GPLv3 you are good to go.  If you are using another license you'll have to check compatibility.  
But, I highly recommend the GPLv3, but everyone has their own views.

**Comment by tibbi** [comment]
I definitely dont support app editing and republishing

**Comment by tibbi** [comment]
they seem to have updated the license already. Not sure when or if someone created a PR there, but I can close it already
