### ISSUE TITLE
record voice, while on whatsapp or telegram calls.

### ISSUE THREAD

**Issue by mehdiMj-ir** [SimpleMobileTools/Simple-Voice-Recorder#43]
Please add record whatsapp or telegram option. it could be huge favor :)
*huawei nova 7i*
![Screenshot_20210108_164043_com simplemobiletools voicerecorder](https://user-images.githubusercontent.com/20270329/104019318-96cd0c80-51d0-11eb-960e-f68a66e154f0.jpg)

**Comment by mehdiMj-ir** [comment]
After all these features, you should call this app **Advanced Voice Recorder** 😁

**Comment by tibbi** [comment]
I dont think it is possible, recording anything is difficult on Android. Dont really expect having it
