### ISSUE TITLE
Allow recording to be saved in app data directory

### ISSUE THREAD

**Issue by MPeti1** [SimpleMobileTools/Simple-Voice-Recorder#60]
Sometimes I worry that through the recordings any app could have access to the microphone in an indirect way.
I understand that it's me who allowed reading of the public storage for all apps where I did, but usually it's a necessary bad for apps to be usable, and since on android you can't give access to only a certain directory of the storage, I can't make sure that those apps won't have access to the recordings.

I was thinking about what could be done to mitigate this, and while I see the shortcomings, I think it might be useful to allow saving recordings to the **internal** app data directory, `/data/data/com.simplemobiletools.voicerecorder`.
Since this can be confusing for new users, this could be a hidden option, either hidden in the menu, or only activatable by manually editing the `Prefs.xml` file.
What I tried is to edit the `internal_storage_path` in the mentioned file, but on next start it was imemdiately reset to `/storage/emulated/0`.

I see the shortcoming that it's kind of hard to access, because you either need root or ADB, but I don't have any better idea.
Though I think this might not be such a big problem, because one can share or "open with" the recordings to an other app.

**Comment by tibbi** [comment]
that is a too advanced function, dont really expect having it

**Comment by landry314** [comment]
This is what Android wants now... Save it in /Android/data/
