### ISSUE TITLE
[Feature Request] Save real MP3 files

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/Simple-Voice-Recorder#62]
Hi,

When I select in the options to have an MP3 file instead of M4A, it's still M4A but with different extension. It's wrong, because MP3 and M4A are two different containers that can have audio encoded differently, so we can't just change the extension.

I've seen issues #1, #19, and #21 but despite they are closed, MP3 files created by the app are still just M4A files with manually changed extension. It's a problem since not every media player can handle M4A files when they can play MP3. 

I know that MediaRecorder can't encode files to MP3, so maybe some external solution for conversion should be used instead, e.g. <https://github.com/cmeng-git/ffmpeg-android>.

**Comment by tibbi** [comment]
should be fixed in 5.8.0
