### ISSUE TITLE
Bug: playback stops on screen rotation

### ISSUE THREAD

**Issue by Self-Perfection** [SimpleMobileTools/Simple-Voice-Recorder#70]
Steps to reproduce:
1. Open list of recordings
2. Start playback of one of the recordings
3. Rotate a device horizontally

Result:
Screen rotates and playback stops

Expected results:
Screen rotates and playbacks continues uninterrupted.

**Comment by Aga-C** [comment]
This issue is already fixed in the newest release (5.6.1), Should be closed.
