### ISSUE TITLE
Pixel 5 cracking sounds

### ISSUE THREAD

**Issue by mcclaneonfire** [SimpleMobileTools/Simple-Voice-Recorder#77]
Hello there, 
anyone also having sound problems with their Android or even Pixel 5 with the recording app?
It records cracks and does not sound clear. Reinstallation did not solve it. The onboard Google Recorder app sounds just fine ;) So it's not Microphone. 

Kind regards, Tobias

**Comment by HeMe2** [comment]
I have exactly the same problem on Pixel 5 with GrapheneOS (Android 12). 

Another open source recording app "Audio Recorder" is working fine...
So it's not the microphone.

Best

**Comment by tibbi** [comment]
starting with 5.10.3 you will be able to change the audio source, that should help fixing it
