### ISSUE TITLE
[Crash] Deny Permissions 

### ISSUE THREAD

**Issue by Anshul1507** [SimpleMobileTools/Simple-Voice-Recorder#84]
After denying permission two times, the app is crashing while opening till we allow the permission from settings.

Ref Video: 

https://user-images.githubusercontent.com/38963667/147447509-89639c1c-8f97-403f-874c-991dcd30ddbd.mp4

**Comment by Anshul1507** [comment]
@tibbi I would love to solve this issue if assigned.

**Comment by tibbi** [comment]
sure, you can solve it

**Comment by Anshul1507** [comment]
yeah, just had some workaround for this closing reason, will show the pop-up dialog with the flow for the user to go to the app settings to allow the permission.

**Comment by Anshul1507** [comment]
As I went through the code, I have to change the Simple-Commons permission file for making the change in this repo, and if I am not wrong this is the base repo for all your projects.

**Comment by tibbi** [comment]
we should just show some toast at calling Finish, not change anything else

**Comment by Anshul1507** [comment]
We can show that, but it is not sure that each time user will be able to understand like we are showing the toast for permission allowance. It's just a more interactive UX if we show one dialog box in place of toast message. 

You can check the demo [here](https://github.com/Anshul1507/Multiple-Permission-Android), what i want to add on here

**Comment by tibbi** [comment]
no need to create imaginary issues if there are none... If someone declines the permission multiple times, of course he won't be able to use the app

**Comment by Anshul1507** [comment]
Alright, but it's just been a fair advantage if we have that.

**Comment by Anshul1507** [comment]
We can close this issue if this is not going ahead.

**Comment by Aga-C** [comment]
@Anshul1507 Showing toast for missing permission is also done in Simple Gallery. There is even a string in Simple Commons to use for no audio permission. I think that the only thing missing is showing a toast with it in `else` of `handlePermission` in MainActivity.

**Comment by Anshul1507** [comment]
yeah, that is there, but I was going ahead to make better UX and flow.
