### ISSUE TITLE
Native WaveForm Library

### ISSUE THREAD

**Issue by Anshul1507** [SimpleMobileTools/Simple-Voice-Recorder#85]
This app is using an external library for creating waveform, there is one sample type of waveform given for Audio player by [Google Git](https://android.googlesource.com/platform/development/+/master/samples/ApiDemos/src/com/example/android/apis/media/AudioFxDemo.java), I created the same for audio recorder waveform for my project.

Would love to contribute this to your project.

Ref Video: 

https://user-images.githubusercontent.com/38963667/147449503-451a371d-e9d3-4220-a559-d771c2e5dadb.mp4

**Comment by tibbi** [comment]
there is already a waveform used, not sure why should it be changed
